// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfu1gpJwbuLczaMvaAg8JfwhWNLBfqYE4',
    appId: '1:209758687103:web:852aec41c31239925f544a',
    messagingSenderId: '209758687103',
    projectId: 'arcane-ops',
    authDomain: 'arcane-ops.firebaseapp.com',
    storageBucket: 'arcane-ops.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfu1gpJwbuLczaMvaAg8JfwhWNLBfqYE4',
    appId: '1:209758687103:android:852aec41c31239925f544a',
    messagingSenderId: '209758687103',
    projectId: 'arcane-ops',
    storageBucket: 'arcane-ops.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfu1gpJwbuLczaMvaAg8JfwhWNLBfqYE4',
    appId: '1:209758687103:ios:852aec41c31239925f544a',
    messagingSenderId: '209758687103',
    projectId: 'arcane-ops',
    storageBucket: 'arcane-ops.firebasestorage.app',
    iosBundleId: 'com.example.arcaneOps',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAfu1gpJwbuLczaMvaAg8JfwhWNLBfqYE4',
    appId: '1:209758687103:macos:852aec41c31239925f544a',
    messagingSenderId: '209758687103',
    projectId: 'arcane-ops',
    storageBucket: 'arcane-ops.firebasestorage.app',
    iosBundleId: 'com.example.arcaneOps',
  );
}
