name: Dart CI

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Récupérer le code
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Configurer Dart (au lieu de Flutter)
      - name: Set up Dart
        uses: dart-lang/setup-dart@v1

      # 3. Installer les dépendances
      - name: Install dependencies
        run: dart pub get

      # 4. Compiler en exécutable binaire autonome
      - name: Compile Dart app
        run: dart compile exe bin/main.dart -o my_app

      # 5. Récupérer le fichier exécutable
      - name: Upload executable
        uses: actions/upload-artifact@v4
        with:
          name: dart-executable
          path: my_app
